// Google Maps API key
export const GOOGLE_MAP_KEY = 'AIzaSyAbHovFzwvdwf81BCJo0HF3YMN6lfwqsVY';
// Foursquare Client ID
export const FOURSQUARE_CLI_ID = 'GFM3BOP5JNJRHBHVKDG1HZLP33M2VKFIZIRCVOTEDLONKXRX';
// Foursquare Client Secret
export const FOURSQUARE_CLI_SECRET = 'IVQC3KNE0MKFESFY4RID5GMTN0SQFJAUQYPME4ADYPMM102S';